-- MySQL Script generated by MySQL Workbench
-- Mon Jul 25 11:35:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uraa_tramite
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uraa_tramite` ;

-- -----------------------------------------------------
-- Schema uraa_tramite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uraa_tramite` DEFAULT CHARACTER SET utf8 ;
USE `uraa_tramite` ;

-- -----------------------------------------------------
-- Table `uraa_tramite`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tipo_usuario` (
  `idTipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idTipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`usuario` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idTipo_usuario` INT NOT NULL,
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `tipo_documento` VARCHAR(50) NOT NULL,
  `nro_documento` VARCHAR(12) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `celular` VARCHAR(9) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `confirmed` TINYINT(1) NOT NULL DEFAULT 0,
  `confirmation_code` VARCHAR(25) NULL DEFAULT NULL,
  `reset_password` VARCHAR(25) NULL DEFAULT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_tipo_usuario_idx` (`idTipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`idTipo_usuario`)
    REFERENCES `uraa_tramite`.`tipo_usuario` (`idTipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tipo_tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tipo_tramite` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tipo_tramite` (
  `idTipo_tramite` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTipo_tramite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`unidad` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`unidad` (
  `idUnidad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUnidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tipo_tramite_unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tipo_tramite_unidad` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tipo_tramite_unidad` (
  `idTipo_tramite_unidad` INT NOT NULL AUTO_INCREMENT,
  `idTipo_tramite` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `costo` DOUBLE NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTipo_tramite_unidad`),
  INDEX `fk_tipo_tramite_unidad_tipo_tramite1_idx` (`idTipo_tramite` ASC) VISIBLE,
  INDEX `fk_tipo_tramite_unidad_unidad1_idx` (`idUnidad` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_tramite_unidad_tipo_tramite1`
    FOREIGN KEY (`idTipo_tramite`)
    REFERENCES `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_tramite_unidad_unidad1`
    FOREIGN KEY (`idUnidad`)
    REFERENCES `uraa_tramite`.`unidad` (`idUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`voucher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`voucher` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`voucher` (
  `idVoucher` INT NOT NULL AUTO_INCREMENT,
  `idEntidad` INT NOT NULL,
  `nro_operacion` VARCHAR(45) NOT NULL,
  `fecha_operacion` DATE NOT NULL,
  `archivo` VARCHAR(255) NULL,
  `des_estado_voucher` VARCHAR(45) NOT NULL DEFAULT 'PENDIENTE',
  `idUsuario_aprobador` INT NULL,
  `validado` TINYINT(1) NOT NULL DEFAULT 0,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idVoucher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`estado_tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`estado_tramite` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`estado_tramite` (
  `idEstado_tramite` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `color` VARCHAR(10) NOT NULL,
  `icono` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado_tramite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`dependencia` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`dependencia` (
  `idDependencia` INT NOT NULL AUTO_INCREMENT,
  `idUnidad` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idDependencia`, `idUnidad`),
  INDEX `fk_dependencia_unidad1_idx` (`idUnidad` ASC) VISIBLE,
  CONSTRAINT `fk_dependencia_unidad1`
    FOREIGN KEY (`idUnidad`)
    REFERENCES `uraa_tramite`.`unidad` (`idUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`cronograma_carpeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`cronograma_carpeta` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`cronograma_carpeta` (
  `idCronograma_carpeta` INT NOT NULL AUTO_INCREMENT,
  `idDependencia` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `fecha_cierre_alumno` DATE NOT NULL,
  `fecha_cierre_secretaria` DATE NOT NULL,
  `fecha_cierre_decanato` DATE NOT NULL,
  `fecha_cierre_uraa` DATE NOT NULL,
  `fecha_colacion` DATE NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idCronograma_carpeta`),
  INDEX `fk_cronograma_carpeta_dependencia1_idx` (`idDependencia` ASC, `idUnidad` ASC) VISIBLE,
  CONSTRAINT `fk_cronograma_carpeta_dependencia1`
    FOREIGN KEY (`idDependencia` , `idUnidad`)
    REFERENCES `uraa_tramite`.`dependencia` (`idDependencia` , `idUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`motivo_certificado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`motivo_certificado` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`motivo_certificado` (
  `idMotivo_certificado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idMotivo_certificado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`modalidad_titulo_carpeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`modalidad_titulo_carpeta` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`modalidad_titulo_carpeta` (
  `idModalidad_titulo_carpeta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `desripcion` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idModalidad_titulo_carpeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tramite_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tramite_detalle` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tramite_detalle` (
  `idTramite_detalle` INT NOT NULL AUTO_INCREMENT,
  `idCronograma_carpeta` INT NULL DEFAULT NULL,
  `idModalidad_titulo_carpeta` INT NULL DEFAULT NULL,
  `idMotivo_certificado` INT NULL DEFAULT NULL,
  `solicitud_certificado` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idTramite_detalle`),
  INDEX `fk_tramite_detalle_cronograma1_idx` (`idCronograma_carpeta` ASC) VISIBLE,
  INDEX `fk_tramite_detalle_motivo_certificado1_idx` (`idMotivo_certificado` ASC) VISIBLE,
  INDEX `fk_tramite_detalle_modalidad_titulo_carpeta1_idx` (`idModalidad_titulo_carpeta` ASC) VISIBLE,
  CONSTRAINT `fk_tramite_detalle_cronograma1`
    FOREIGN KEY (`idCronograma_carpeta`)
    REFERENCES `uraa_tramite`.`cronograma_carpeta` (`idCronograma_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_detalle_motivo_certificado1`
    FOREIGN KEY (`idMotivo_certificado`)
    REFERENCES `uraa_tramite`.`motivo_certificado` (`idMotivo_certificado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_detalle_modalidad_titulo_carpeta1`
    FOREIGN KEY (`idModalidad_titulo_carpeta`)
    REFERENCES `uraa_tramite`.`modalidad_titulo_carpeta` (`idModalidad_titulo_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tramite` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tramite` (
  `idTramite` INT NOT NULL AUTO_INCREMENT,
  `idTramite_detalle` INT NOT NULL,
  `idTipo_tramite_unidad` INT NOT NULL,
  `idVoucher` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `nro_tramite` CHAR(10) NOT NULL,
  `idUnidad` INT NOT NULL,
  `idDependencia` INT NOT NULL,
  `idDependencia_detalle` INT NOT NULL,
  `nro_matricula` VARCHAR(45) NOT NULL,
  `sede` VARCHAR(45) NOT NULL,
  `idEstado_tramite` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `firma_tramite` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `exonerado_archivo` VARCHAR(255) NULL,
  PRIMARY KEY (`idTramite`),
  INDEX `fk_tramite_tipo_tramite_unidad1_idx` (`idTipo_tramite_unidad` ASC) VISIBLE,
  INDEX `fk_tramite_voucher1_idx` (`idVoucher` ASC) VISIBLE,
  INDEX `fk_tramite_estado_tramite1_idx` (`idEstado_tramite` ASC) VISIBLE,
  INDEX `fk_tramite_tramite_detalle1_idx` (`idTramite_detalle` ASC) VISIBLE,
  INDEX `fk_tramite_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tramite_tipo_tramite_unidad1`
    FOREIGN KEY (`idTipo_tramite_unidad`)
    REFERENCES `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_voucher1`
    FOREIGN KEY (`idVoucher`)
    REFERENCES `uraa_tramite`.`voucher` (`idVoucher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_estado_tramite1`
    FOREIGN KEY (`idEstado_tramite`)
    REFERENCES `uraa_tramite`.`estado_tramite` (`idEstado_tramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_tramite_detalle1`
    FOREIGN KEY (`idTramite_detalle`)
    REFERENCES `uraa_tramite`.`tramite_detalle` (`idTramite_detalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `uraa_tramite`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`requisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`requisito` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`requisito` (
  `idRequisito` INT NOT NULL AUTO_INCREMENT,
  `idTipo_tramite` INT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `extension` VARCHAR(10) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idRequisito`),
  INDEX `fk_requisito_tipo_tramite1_idx` (`idTipo_tramite` ASC) VISIBLE,
  CONSTRAINT `fk_requisito_tipo_tramite1`
    FOREIGN KEY (`idTipo_tramite`)
    REFERENCES `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tramite_requisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tramite_requisito` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tramite_requisito` (
  `idTramite` INT NOT NULL,
  `idRequisito` INT NOT NULL,
  `archivo` VARCHAR(100) NULL,
  `idUsuario_aprobador` INT NULL,
  `validado` TINYINT(1) NOT NULL DEFAULT 0,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTramite`, `idRequisito`),
  INDEX `fk_tramite_requisito_requisito1_idx` (`idRequisito` ASC) VISIBLE,
  CONSTRAINT `fk_tramite_requisito_tramite1`
    FOREIGN KEY (`idTramite`)
    REFERENCES `uraa_tramite`.`tramite` (`idTramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_requisito_requisito1`
    FOREIGN KEY (`idRequisito`)
    REFERENCES `uraa_tramite`.`requisito` (`idRequisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`escuela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`escuela` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`escuela` (
  `idEscuela` INT NOT NULL AUTO_INCREMENT,
  `idDependencia` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `idSGA_PREG` INT NULL,
  `idSUV_PREG` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `denominacion` VARCHAR(100) NOT NULL,
  `descripcion_grado` VARCHAR(100) NOT NULL,
  `descripcion_titulo` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idEscuela`, `idDependencia`, `idUnidad`),
  INDEX `fk_escuela_dependencia1_idx` (`idUnidad` ASC, `idDependencia` ASC) VISIBLE,
  CONSTRAINT `fk_escuela_dependencia1`
    FOREIGN KEY (`idUnidad` , `idDependencia`)
    REFERENCES `uraa_tramite`.`dependencia` (`idUnidad` , `idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`mencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`mencion` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`mencion` (
  `idMencion` INT NOT NULL AUTO_INCREMENT,
  `idDependencia` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `idSGA_SE` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `denominacion` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idMencion`, `idDependencia`, `idUnidad`),
  INDEX `fk_escuela_dependencia1_idx` (`idUnidad` ASC, `idDependencia` ASC) VISIBLE,
  CONSTRAINT `fk_escuela_dependencia10`
    FOREIGN KEY (`idUnidad` , `idDependencia`)
    REFERENCES `uraa_tramite`.`dependencia` (`idUnidad` , `idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`programa` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`programa` (
  `idPrograma` INT NOT NULL AUTO_INCREMENT,
  `idDependencia` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `idSGA_SE` INT NOT NULL,
  `denominacion` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idPrograma`, `idDependencia`, `idUnidad`),
  INDEX `fk_escuela_dependencia1_idx` (`idUnidad` ASC, `idDependencia` ASC) VISIBLE,
  CONSTRAINT `fk_escuela_dependencia100`
    FOREIGN KEY (`idUnidad` , `idDependencia`)
    REFERENCES `uraa_tramite`.`dependencia` (`idUnidad` , `idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`historial_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`historial_estado` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`historial_estado` (
  `idHistorial_estado` INT NOT NULL AUTO_INCREMENT,
  `idEstado_actual` INT NULL,
  `idEstado_nuevo` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `idTramite` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idHistorial_estado`),
  INDEX `fk_historial_estado_tramite1_idx` (`idTramite` ASC) VISIBLE,
  INDEX `fk_historial_estado_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_historial_estado_tramite1`
    FOREIGN KEY (`idTramite`)
    REFERENCES `uraa_tramite`.`tramite` (`idTramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_estado_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `uraa_tramite`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`tipo_usuario` (`idTipo_usuario`, `nombre`, `estado`) VALUES (DEFAULT, 'ALUMNO', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`usuario` (`idUsuario`, `idTipo_usuario`, `username`, `password`, `nombres`, `apellidos`, `tipo_documento`, `nro_documento`, `correo`, `celular`, `sexo`, `confirmed`, `confirmation_code`, `reset_password`, `estado`) VALUES (DEFAULT, 1, 'kjuarez', '$2y$10$J32LozOcUvuZ3vUEZJePeeO3gnu//yo8XGpZ6ovV81sbTgGuIB8Ra', 'KEVIN', 'JUAREZ', '1', '75411199', 'kmuncibay@unitru.edu.pe', '96521542', 'M', 0, NULL, NULL, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`tipo_tramite`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`, `descripcion`, `estado`) VALUES (DEFAULT, 'CERTIFICADO DE ESTUDIOS', 0);
INSERT INTO `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`, `descripcion`, `estado`) VALUES (DEFAULT, 'ELABORACIÓN DE CARPETA', 0);
INSERT INTO `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`, `descripcion`, `estado`) VALUES (DEFAULT, 'CARNÉ UNIVERSITARIO', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`unidad`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`unidad` (`idUnidad`, `descripcion`, `estado`) VALUES (DEFAULT, 'PREGRADO', 1);
INSERT INTO `uraa_tramite`.`unidad` (`idUnidad`, `descripcion`, `estado`) VALUES (DEFAULT, 'POSTGRADO - DOCTORADO', 1);
INSERT INTO `uraa_tramite`.`unidad` (`idUnidad`, `descripcion`, `estado`) VALUES (DEFAULT, 'POSTGRADO - MAESTRÍA', 1);
INSERT INTO `uraa_tramite`.`unidad` (`idUnidad`, `descripcion`, `estado`) VALUES (DEFAULT, 'SEGUNDA ESPECIALIDAD', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`tipo_tramite_unidad`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 1 AÑO', 15, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 2 AÑOS', 30, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 3 AÑOS', 45, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 4 AÑOS', 60, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 5 AÑOS', 75, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 6 AÑOS', 90, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 7 AÑOS', 105, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 2, 'CERTIFICADO DE ESTUDIOS DE 1 AÑO', 15, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 2, 'CERTIFICADO DE ESTUDIOS DE 2 AÑOS', 30, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 2, 'CERTIFICADO DE ESTUDIOS DE 3 AÑOS', 45, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 3, 'CERTIFICADO DE ESTUDIOS DE 1 AÑO', 15, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 3, 'CERTIFICADO DE ESTUDIOS DE 2 AÑOS', 30, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 4, 'CERTIFICADO DE ESTUDIOS DE 1 AÑO', 15, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `estado`) VALUES (DEFAULT, 1, 4, 'CERTIFICADO DE ESTUDIOS DE 2 AÑOS', 30, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`estado_tramite`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRAMITE REGISTRADO', 'EXITOSAMENTE', '#01438e', 'icon-check', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'VALIDANDO VOUCHER POR TESORERÍA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'VOUCHER VALIDADO', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE OBSERVADO', 'VOUCHER RECHAZADO', '#E12E15', 'icon-cross', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'PENDIENTE DE ASIGNACIÓN EN URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'ASIGNADO EN URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'VALIDANDO DOCUMENTACIÓN EN URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'DOCUMENTOS VALIDADOS EN URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE OBSERVADO', 'DOCUMENTOS RECHAZADOS EN URAA', '#E12E15', 'icon-cross', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'CERTIFICADO GENERADO', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'PENDIENTE DE FIRMA DE DIRECTOR URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'FIRMADO POR DIRECTOR URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'PENDIENTE DE FIRMA DE DECANO', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'FIRMADO POR DECANO', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRAMITE FINALIZADO', 'EXITOSAMENTE', '#2CAC16', 'icon-check', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`dependencia`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE INGENIERIA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE CIENCIAS BIOLOGICAS', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 4, 'SEGUNDA ESPECIALIDAD PROFESIONAL DE ENFERMERIA', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`cronograma_carpeta`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`cronograma_carpeta` (`idCronograma_carpeta`, `idDependencia`, `idUnidad`, `fecha_cierre_alumno`, `fecha_cierre_secretaria`, `fecha_cierre_decanato`, `fecha_cierre_uraa`, `fecha_colacion`, `estado`) VALUES (DEFAULT, 1, 1, '2022-07-23', '2022-07-23', '2022-07-23', '2022-07-23', '2022-07-23', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`motivo_certificado`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`motivo_certificado` (`idMotivo_certificado`, `nombre`, `descripcion`, `estado`) VALUES (DEFAULT, 'TRÁMITE INTERNO', 'CERTIFICADO DIGITAL PARA TRÁMITE INTERNO', DEFAULT);
INSERT INTO `uraa_tramite`.`motivo_certificado` (`idMotivo_certificado`, `nombre`, `descripcion`, `estado`) VALUES (DEFAULT, 'TRÁMITE EXTERNO', 'CERTIFICADO DIGITAL PARA TRÁMITE EXTERNO', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`modalidad_titulo_carpeta`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`modalidad_titulo_carpeta` (`idModalidad_titulo_carpeta`, `nombre`, `desripcion`, `estado`) VALUES (DEFAULT, 'motivo1', 'descripcion', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`requisito`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite`, `descripcion`, `extension`, `estado`) VALUES (DEFAULT, 2, 'CONSTANCIA DE EXONERACIÓN', 'pdf', DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite`, `descripcion`, `extension`, `estado`) VALUES (DEFAULT, 1, 'COPIA DE DNI', 'pdf', DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite`, `descripcion`, `extension`, `estado`) VALUES (DEFAULT, 1, 'FOTO TAMAÑO CARNET', 'jpg', DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite`, `descripcion`, `extension`, `estado`) VALUES (DEFAULT, 3, 'DENUNCIA POLICIAL', 'pdf', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`escuela`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 1, 1, 73, 21, 'INGENIERIA DE SISTEMAS', 'ESCUELA PROFESIONAL DE INGENIERIA DE SISTEMAS', 'DESCRIPCION GRADO', 'DESCRIPCION TITULO', 1);

COMMIT;

