-- MySQL Script generated by MySQL Workbench
-- Fri Sep 23 09:22:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uraa_tramite
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uraa_tramite` ;

-- -----------------------------------------------------
-- Schema uraa_tramite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uraa_tramite` DEFAULT CHARACTER SET utf8 ;
USE `uraa_tramite` ;

-- -----------------------------------------------------
-- Table `uraa_tramite`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tipo_usuario` (
  `idTipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`usuario` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idTipo_usuario` INT NOT NULL,
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `tipo_documento` VARCHAR(50) NOT NULL,
  `nro_documento` VARCHAR(12) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `celular` VARCHAR(9) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `confirmed` TINYINT(1) NOT NULL DEFAULT 0,
  `confirmation_code` VARCHAR(25) NULL DEFAULT NULL,
  `reset_password` VARCHAR(25) NULL DEFAULT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_tipo_usuario_idx` (`idTipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`idTipo_usuario`)
    REFERENCES `uraa_tramite`.`tipo_usuario` (`idTipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tipo_tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tipo_tramite` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tipo_tramite` (
  `idTipo_tramite` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTipo_tramite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`unidad` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`unidad` (
  `idUnidad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUnidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tipo_tramite_unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tipo_tramite_unidad` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tipo_tramite_unidad` (
  `idTipo_tramite_unidad` INT NOT NULL AUTO_INCREMENT,
  `idTipo_tramite` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `costo` DOUBLE NOT NULL,
  `costo_exonerado` DOUBLE NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTipo_tramite_unidad`),
  INDEX `fk_tipo_tramite_unidad_tipo_tramite1_idx` (`idTipo_tramite` ASC) VISIBLE,
  INDEX `fk_tipo_tramite_unidad_unidad1_idx` (`idUnidad` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_tramite_unidad_tipo_tramite1`
    FOREIGN KEY (`idTipo_tramite`)
    REFERENCES `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_tramite_unidad_unidad1`
    FOREIGN KEY (`idUnidad`)
    REFERENCES `uraa_tramite`.`unidad` (`idUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`voucher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`voucher` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`voucher` (
  `idVoucher` INT NOT NULL AUTO_INCREMENT,
  `entidad` VARCHAR(50) NOT NULL,
  `nro_operacion` VARCHAR(45) NOT NULL,
  `fecha_operacion` DATE NOT NULL,
  `archivo` VARCHAR(255) NULL,
  `des_estado_voucher` VARCHAR(45) NOT NULL DEFAULT 'PENDIENTE',
  `idUsuario_aprobador` INT NULL,
  `validado` TINYINT(1) NOT NULL DEFAULT 0,
  `comentario` VARCHAR(255) NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idVoucher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`estado_tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`estado_tramite` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`estado_tramite` (
  `idEstado_tramite` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `color` VARCHAR(10) NOT NULL,
  `icono` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado_tramite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`dependencia` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`dependencia` (
  `idDependencia` INT NOT NULL AUTO_INCREMENT,
  `idUnidad` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idDependencia`, `idUnidad`),
  INDEX `fk_dependencia_unidad1_idx` (`idUnidad` ASC) VISIBLE,
  CONSTRAINT `fk_dependencia_unidad1`
    FOREIGN KEY (`idUnidad`)
    REFERENCES `uraa_tramite`.`unidad` (`idUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`cronograma_carpeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`cronograma_carpeta` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`cronograma_carpeta` (
  `idCronograma_carpeta` INT NOT NULL AUTO_INCREMENT,
  `idDependencia` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `fecha_cierre_alumno` DATE NOT NULL,
  `fecha_cierre_secretaria` DATE NOT NULL,
  `fecha_cierre_decanato` DATE NOT NULL,
  `fecha_cierre_uraa` DATE NOT NULL,
  `fecha_colacion` DATE NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idCronograma_carpeta`),
  INDEX `fk_cronograma_carpeta_dependencia1_idx` (`idDependencia` ASC, `idUnidad` ASC) VISIBLE,
  CONSTRAINT `fk_cronograma_carpeta_dependencia1`
    FOREIGN KEY (`idDependencia` , `idUnidad`)
    REFERENCES `uraa_tramite`.`dependencia` (`idDependencia` , `idUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`motivo_certificado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`motivo_certificado` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`motivo_certificado` (
  `idMotivo_certificado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idMotivo_certificado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`modalidad_titulo_carpeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`modalidad_titulo_carpeta` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`modalidad_titulo_carpeta` (
  `idModalidad_titulo_carpeta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `desripcion` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idModalidad_titulo_carpeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tramite_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tramite_detalle` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tramite_detalle` (
  `idTramite_detalle` INT NOT NULL AUTO_INCREMENT,
  `idCronograma_carpeta` INT NULL DEFAULT NULL,
  `idModalidad_titulo_carpeta` INT NULL DEFAULT NULL,
  `idMotivo_certificado` INT NULL DEFAULT NULL,
  `certificado_final` VARCHAR(100) NULL,
  `codigo_certificado` VARCHAR(100) NULL,
  `pass_certificado` VARCHAR(100) NULL,
  `constancia_final` VARCHAR(100) NULL,
  PRIMARY KEY (`idTramite_detalle`),
  INDEX `fk_tramite_detalle_cronograma1_idx` (`idCronograma_carpeta` ASC) VISIBLE,
  INDEX `fk_tramite_detalle_motivo_certificado1_idx` (`idMotivo_certificado` ASC) VISIBLE,
  INDEX `fk_tramite_detalle_modalidad_titulo_carpeta1_idx` (`idModalidad_titulo_carpeta` ASC) VISIBLE,
  CONSTRAINT `fk_tramite_detalle_cronograma1`
    FOREIGN KEY (`idCronograma_carpeta`)
    REFERENCES `uraa_tramite`.`cronograma_carpeta` (`idCronograma_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_detalle_motivo_certificado1`
    FOREIGN KEY (`idMotivo_certificado`)
    REFERENCES `uraa_tramite`.`motivo_certificado` (`idMotivo_certificado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_detalle_modalidad_titulo_carpeta1`
    FOREIGN KEY (`idModalidad_titulo_carpeta`)
    REFERENCES `uraa_tramite`.`modalidad_titulo_carpeta` (`idModalidad_titulo_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tramite` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tramite` (
  `idTramite` INT NOT NULL AUTO_INCREMENT,
  `idTramite_detalle` INT NOT NULL,
  `idTipo_tramite_unidad` INT NOT NULL,
  `idVoucher` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `nro_tramite` CHAR(10) NOT NULL,
  `idUnidad` INT NOT NULL,
  `idDependencia` INT NOT NULL,
  `idDependencia_detalle` INT NOT NULL,
  `nro_matricula` VARCHAR(45) NOT NULL,
  `sede` VARCHAR(45) NOT NULL,
  `exonerado_archivo` VARCHAR(255) NULL,
  `comentario` VARCHAR(255) NULL,
  `idEstado_tramite` INT NOT NULL,
  `firma_tramite` VARCHAR(255) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `idUsuario_asignado` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTramite`),
  INDEX `fk_tramite_tipo_tramite_unidad1_idx` (`idTipo_tramite_unidad` ASC) VISIBLE,
  INDEX `fk_tramite_voucher1_idx` (`idVoucher` ASC) VISIBLE,
  INDEX `fk_tramite_estado_tramite1_idx` (`idEstado_tramite` ASC) VISIBLE,
  INDEX `fk_tramite_tramite_detalle1_idx` (`idTramite_detalle` ASC) VISIBLE,
  INDEX `fk_tramite_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tramite_tipo_tramite_unidad1`
    FOREIGN KEY (`idTipo_tramite_unidad`)
    REFERENCES `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_voucher1`
    FOREIGN KEY (`idVoucher`)
    REFERENCES `uraa_tramite`.`voucher` (`idVoucher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_estado_tramite1`
    FOREIGN KEY (`idEstado_tramite`)
    REFERENCES `uraa_tramite`.`estado_tramite` (`idEstado_tramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_tramite_detalle1`
    FOREIGN KEY (`idTramite_detalle`)
    REFERENCES `uraa_tramite`.`tramite_detalle` (`idTramite_detalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `uraa_tramite`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`requisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`requisito` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`requisito` (
  `idRequisito` INT NOT NULL AUTO_INCREMENT,
  `idTipo_tramite_unidad` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `extension` VARCHAR(10) NOT NULL,
  `responsable` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idRequisito`),
  INDEX `fk_requisito_tipo_tramite_unidad1_idx` (`idTipo_tramite_unidad` ASC) VISIBLE,
  CONSTRAINT `fk_requisito_tipo_tramite_unidad1`
    FOREIGN KEY (`idTipo_tramite_unidad`)
    REFERENCES `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`tramite_requisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`tramite_requisito` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`tramite_requisito` (
  `idTramite` INT NOT NULL,
  `idRequisito` INT NOT NULL,
  `archivo` VARCHAR(255) NULL,
  `idUsuario_aprobador` INT NULL,
  `validado` TINYINT(1) NOT NULL DEFAULT 0,
  `comentario` VARCHAR(255) NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `des_estado_requisito` VARCHAR(45) NOT NULL DEFAULT 'PENDIENTE',
  PRIMARY KEY (`idTramite`, `idRequisito`),
  INDEX `fk_tramite_requisito_requisito1_idx` (`idRequisito` ASC) VISIBLE,
  CONSTRAINT `fk_tramite_requisito_tramite1`
    FOREIGN KEY (`idTramite`)
    REFERENCES `uraa_tramite`.`tramite` (`idTramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tramite_requisito_requisito1`
    FOREIGN KEY (`idRequisito`)
    REFERENCES `uraa_tramite`.`requisito` (`idRequisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`escuela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`escuela` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`escuela` (
  `idEscuela` INT NOT NULL AUTO_INCREMENT,
  `idDependencia` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `idSGA_PREG` INT NULL,
  `idSUV_PREG` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `denominacion` VARCHAR(100) NOT NULL,
  `descripcion_grado` VARCHAR(100) NOT NULL,
  `descripcion_titulo` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idEscuela`, `idDependencia`, `idUnidad`),
  INDEX `fk_escuela_dependencia1_idx` (`idUnidad` ASC, `idDependencia` ASC) VISIBLE,
  CONSTRAINT `fk_escuela_dependencia1`
    FOREIGN KEY (`idUnidad` , `idDependencia`)
    REFERENCES `uraa_tramite`.`dependencia` (`idUnidad` , `idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`mencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`mencion` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`mencion` (
  `idMencion` INT NOT NULL AUTO_INCREMENT,
  `idDependencia` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `idSGA_SE` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `denominacion` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idMencion`, `idDependencia`, `idUnidad`),
  INDEX `fk_escuela_dependencia1_idx` (`idUnidad` ASC, `idDependencia` ASC) VISIBLE,
  CONSTRAINT `fk_escuela_dependencia10`
    FOREIGN KEY (`idUnidad` , `idDependencia`)
    REFERENCES `uraa_tramite`.`dependencia` (`idUnidad` , `idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`programa` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`programa` (
  `idPrograma` INT NOT NULL AUTO_INCREMENT,
  `idDependencia` INT NOT NULL,
  `idUnidad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `idSGA_SE` INT NOT NULL,
  `denominacion` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idPrograma`, `idDependencia`, `idUnidad`),
  INDEX `fk_escuela_dependencia1_idx` (`idUnidad` ASC, `idDependencia` ASC) VISIBLE,
  CONSTRAINT `fk_escuela_dependencia100`
    FOREIGN KEY (`idUnidad` , `idDependencia`)
    REFERENCES `uraa_tramite`.`dependencia` (`idUnidad` , `idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uraa_tramite`.`historial_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uraa_tramite`.`historial_estado` ;

CREATE TABLE IF NOT EXISTS `uraa_tramite`.`historial_estado` (
  `idHistorial_estado` INT NOT NULL AUTO_INCREMENT,
  `idEstado_actual` INT NULL,
  `idEstado_nuevo` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `idTramite` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idHistorial_estado`),
  INDEX `fk_historial_estado_tramite1_idx` (`idTramite` ASC) VISIBLE,
  INDEX `fk_historial_estado_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_historial_estado_tramite1`
    FOREIGN KEY (`idTramite`)
    REFERENCES `uraa_tramite`.`tramite` (`idTramite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_estado_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `uraa_tramite`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`tipo_usuario` (`idTipo_usuario`, `nombre`, `estado`) VALUES (1, 'ADMIN', DEFAULT);
INSERT INTO `uraa_tramite`.`tipo_usuario` (`idTipo_usuario`, `nombre`, `estado`) VALUES (2, 'URAA', DEFAULT);
INSERT INTO `uraa_tramite`.`tipo_usuario` (`idTipo_usuario`, `nombre`, `estado`) VALUES (3, 'TESORERÍA', DEFAULT);
INSERT INTO `uraa_tramite`.`tipo_usuario` (`idTipo_usuario`, `nombre`, `estado`) VALUES (4, 'ALUMNO', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`usuario` (`idUsuario`, `idTipo_usuario`, `username`, `password`, `nombres`, `apellidos`, `tipo_documento`, `nro_documento`, `correo`, `celular`, `sexo`, `confirmed`, `confirmation_code`, `reset_password`, `estado`) VALUES (DEFAULT, 1, 'kjuarez', '$2y$10$J32LozOcUvuZ3vUEZJePeeO3gnu//yo8XGpZ6ovV81sbTgGuIB8Ra', 'KEVIN', 'JUAREZ', '1', '75411199', 'kmuncibay@unitru.edu.pe', '96521542', 'M', 1, NULL, NULL, DEFAULT);
INSERT INTO `uraa_tramite`.`usuario` (`idUsuario`, `idTipo_usuario`, `username`, `password`, `nombres`, `apellidos`, `tipo_documento`, `nro_documento`, `correo`, `celular`, `sexo`, `confirmed`, `confirmation_code`, `reset_password`, `estado`) VALUES (DEFAULT, 1, 'curbina', '$2y$10$J32LozOcUvuZ3vUEZJePeeO3gnu//yo8XGpZ6ovV81sbTgGuIB8Ra', 'CESAR', 'URBINA', '1', '74660603', 'curbina@unitru.edu.pe', '95426521', 'M', 1, NULL, NULL, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`tipo_tramite`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`, `descripcion`, `estado`) VALUES (DEFAULT, 'CERTIFICADO DE ESTUDIOS', 1);
INSERT INTO `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`, `descripcion`, `estado`) VALUES (DEFAULT, 'ELABORACIÓN DE CARPETA', 0);
INSERT INTO `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`, `descripcion`, `estado`) VALUES (DEFAULT, 'CARNÉ UNIVERSITARIO', 1);
INSERT INTO `uraa_tramite`.`tipo_tramite` (`idTipo_tramite`, `descripcion`, `estado`) VALUES (DEFAULT, 'CONSTANCIA', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`unidad`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`unidad` (`idUnidad`, `descripcion`, `estado`) VALUES (DEFAULT, 'PREGRADO', 1);
INSERT INTO `uraa_tramite`.`unidad` (`idUnidad`, `descripcion`, `estado`) VALUES (DEFAULT, 'POSTGRADO - DOCTORADO', 1);
INSERT INTO `uraa_tramite`.`unidad` (`idUnidad`, `descripcion`, `estado`) VALUES (DEFAULT, 'POSTGRADO - MAESTRÍA', 1);
INSERT INTO `uraa_tramite`.`unidad` (`idUnidad`, `descripcion`, `estado`) VALUES (DEFAULT, 'SEGUNDA ESPECIALIDAD', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`tipo_tramite_unidad`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (1, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 1 AÑO', 15, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (2, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 2 AÑOS', 30, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (3, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 3 AÑOS', 45, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (4, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 4 AÑOS', 60, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (5, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 5 AÑOS', 75, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (6, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 6 AÑOS', 90, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (7, 1, 1, 'CERTIFICADO DE ESTUDIOS DE 7 AÑOS', 105, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (8, 1, 2, 'CERTIFICADO DE ESTUDIOS DE 1 AÑO', 15, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (9, 1, 2, 'CERTIFICADO DE ESTUDIOS DE 2 AÑOS', 30, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (10, 1, 2, 'CERTIFICADO DE ESTUDIOS DE 3 AÑOS', 45, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (11, 1, 3, 'CERTIFICADO DE ESTUDIOS DE 1 AÑO', 15, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (12, 1, 3, 'CERTIFICADO DE ESTUDIOS DE 2 AÑOS', 30, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (13, 1, 4, 'CERTIFICADO DE ESTUDIOS DE 1 AÑO', 15, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (14, 1, 4, 'CERTIFICADO DE ESTUDIOS DE 2 AÑOS', 30, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (15, 2, 1, 'GRADO DE BACHILLER', 200, 26.1, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (16, 2, 1, 'TÍTULO PROFESIONAL', 250, 26.1, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (17, 3, 1, 'SOLICITUD REGULAR', 16.4, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (18, 3, 1, 'SOLICITUD DE DUPLICADO', 27, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (19, 3, 2, 'SOLICITUD REGULAR', 16.4, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (20, 3, 2, 'SOLICITUD DE DUPLICADO', 27, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (21, 3, 3, 'SOLICITUD REGULAR', 16.4, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (22, 3, 3, 'SOLICITUD DE DUPLICADO', 27, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (23, 3, 4, 'SOLICITUD REGULAR', 16.4, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (24, 3, 4, 'SOLICITUD DE DUPLICADO', 27, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (25, 4, 1, 'TERCIO SUPERIOR', 15, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (26, 4, 1, 'QUINTO SUPERIOR', 15, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (27, 4, 1, 'ORDEN DE MÉRITO', 15, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (28, 4, 1, 'PROMEDIO PONDERADO', 15, 0, 1);
INSERT INTO `uraa_tramite`.`tipo_tramite_unidad` (`idTipo_tramite_unidad`, `idTipo_tramite`, `idUnidad`, `descripcion`, `costo`, `costo_exonerado`, `estado`) VALUES (29, 4, 1, 'EGRESADO', 15, 0, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`estado_tramite`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRAMITE REGISTRADO', 'EXITOSAMENTE', '#01438e', 'icon-check', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'VALIDANDO VOUCHER POR TESORERÍA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'VOUCHER VALIDADO', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE OBSERVADO', 'VOUCHER RECHAZADO', '#E12E15', 'icon-cross', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'PENDIENTE DE ASIGNACIÓN EN URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'ASIGNADO EN URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'VALIDANDO DOCUMENTACIÓN EN URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'DOCUMENTOS VALIDADOS EN URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE OBSERVADO', 'DOCUMENTOS RECHAZADOS EN URAA', '#E12E15', 'icon-cross', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'CERTIFICADO GENERADO', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'PENDIENTE DE FIRMA DE DIRECTOR URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'FIRMADO POR DIRECTOR URAA', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'PENDIENTE DE FIRMA DE DECANO', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRÁMITE EN PROCESO', 'FIRMADO POR DECANO', '#CBBC02', 'icon-ccw', '1');
INSERT INTO `uraa_tramite`.`estado_tramite` (`idEstado_tramite`, `nombre`, `descripcion`, `color`, `icono`, `estado`) VALUES (DEFAULT, 'TRAMITE FINALIZADO', 'EXITOSAMENTE', '#2CAC16', 'icon-check', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`dependencia`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE CIENCIAS AGROPECUARIAS', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE CIENCIAS BIOLOGICAS', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE CIENCIAS DE LA EDUCACION', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE CIENCIAS ECONOMICAS', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE CIENCIAS FISICAS Y MATEMATICAS', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE CIENCIAS MEDICAS', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE CIENCIAS SOCIALES', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE DERECHO Y CIENCIAS POLITICAS', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE EDUCACION', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE EDUCACION Y CIENCIAS DE LA COMUNICACION', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE ENFERMERIA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE FARMACIA Y BIOQUIMICA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE INGENIERIA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE INGENIERIA QUIMICA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE MEDICINA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 1, 'FACULTAD DE ESTOMATOLOGIA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 4, 'SEGUNDA ESPECIALIDAD PROFESIONAL EN ENFERMERÍA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 4, 'SEGUNDA ESPECIALIDAD PROFESIONAL EN CIENCIAS BIOLÓGICAS', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 4, 'SEGUNDA ESPECIALIDAD PROFESIONAL EN ESTIMULACIÓN', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 4, 'SEGUNDA ESPECIALIDAD PROFESIONAL EN TECNOLOGÍA EDUCATIVA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 4, 'SEGUNDA ESPECIALIDAD PROFESIONAL EN FARMACIA Y BIOQUÍMICA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 4, 'SEGUNDA ESPECIALIDAD PROFESIONAL EN MEDICINA', 1);
INSERT INTO `uraa_tramite`.`dependencia` (`idDependencia`, `idUnidad`, `nombre`, `estado`) VALUES (DEFAULT, 4, 'SEGUNDA ESPECIALIDAD PROFESIONAL EN ESTOMATOLOGÍA', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`cronograma_carpeta`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`cronograma_carpeta` (`idCronograma_carpeta`, `idDependencia`, `idUnidad`, `fecha_cierre_alumno`, `fecha_cierre_secretaria`, `fecha_cierre_decanato`, `fecha_cierre_uraa`, `fecha_colacion`, `estado`) VALUES (DEFAULT, 1, 1, '2022-07-23', '2022-07-23', '2022-07-23', '2022-07-23', '2022-07-23', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`motivo_certificado`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`motivo_certificado` (`idMotivo_certificado`, `nombre`, `descripcion`, `estado`) VALUES (DEFAULT, 'TRÁMITE INTERNO', 'CERTIFICADO DIGITAL PARA TRÁMITE INTERNO', DEFAULT);
INSERT INTO `uraa_tramite`.`motivo_certificado` (`idMotivo_certificado`, `nombre`, `descripcion`, `estado`) VALUES (DEFAULT, 'TRÁMITE EXTERNO', 'CERTIFICADO DIGITAL PARA TRÁMITE EXTERNO', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`modalidad_titulo_carpeta`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`modalidad_titulo_carpeta` (`idModalidad_titulo_carpeta`, `nombre`, `desripcion`, `estado`) VALUES (DEFAULT, 'motivo1', 'descripcion', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`tramite_detalle`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`tramite_detalle` (`idTramite_detalle`, `idCronograma_carpeta`, `idModalidad_titulo_carpeta`, `idMotivo_certificado`, `certificado_final`, `codigo_certificado`, `pass_certificado`, `constancia_final`) VALUES (1, NULL, NULL, 1, NULL, NULL, NULL, NULL);
INSERT INTO `uraa_tramite`.`tramite_detalle` (`idTramite_detalle`, `idCronograma_carpeta`, `idModalidad_titulo_carpeta`, `idMotivo_certificado`, `certificado_final`, `codigo_certificado`, `pass_certificado`, `constancia_final`) VALUES (2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`tramite`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`tramite` (`idTramite`, `idTramite_detalle`, `idTipo_tramite_unidad`, `idVoucher`, `idUsuario`, `nro_tramite`, `idUnidad`, `idDependencia`, `idDependencia_detalle`, `nro_matricula`, `sede`, `exonerado_archivo`, `comentario`, `idEstado_tramite`, `firma_tramite`, `estado`, `idUsuario_asignado`, `created_at`, `updated_at`) VALUES (1, 1, 5, 2, 1, '001080922', 1, 13, 29, '1023300217', 'Trujillo', NULL, '', 2, '/storage/firmas_tramites/001080922.jpg', 1, NULL, '2022-09-08 11:01:29', '2022-09-08 11:01:29');
INSERT INTO `uraa_tramite`.`tramite` (`idTramite`, `idTramite_detalle`, `idTipo_tramite_unidad`, `idVoucher`, `idUsuario`, `nro_tramite`, `idUnidad`, `idDependencia`, `idDependencia_detalle`, `nro_matricula`, `sede`, `exonerado_archivo`, `comentario`, `idEstado_tramite`, `firma_tramite`, `estado`, `idUsuario_asignado`, `created_at`, `updated_at`) VALUES (2, 2, 25, 3, 1, '002080922', 1, 13, 29, '1023300217', 'Trujillo', NULL, '', 2, '/storage/firmas_tramites/002080922.jpg', 1, NULL, '2022-09-08 11:14:22', '2022-09-08 11:14:22');

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`requisito`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 1, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 2, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 3, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 4, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 5, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 6, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 7, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 8, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 9, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 10, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 11, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 12, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 13, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 14, 'FOTO CARNET', 'UNA FOTO TAMAÑO CARNET ACTUAL A COLOR CON EL LOGOTIPO DE LA UNT, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 15, 'FOTO PASAPORTE', 'FOTO ACTUAL TAMAÑO PASAPORTE A COLOR CON EL LOGO DE LA UNT FONDO BLANCO', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 15, 'CONSTANCIA DE EXPEDITO', 'CONSTANCIA DE EXPEDITO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 15, 'CONSTANCIA DE NO ADEUDO', 'CONSTANCIA DE NO ADEUDO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 15, 'CONSTANCIA DE PRIMERA MATRICULA Y EGRESADO', 'CONSTANCIA DE PRIMERA MATRICULA Y EGRESADO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 15, 'CERTIFICADO DE ESTUDIOS', 'CERTIFICADO DE ESTUDIOS', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 15, 'COPIA DE DNI', 'COPIA DE DNI LEGIBLE', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 15, 'RESOLUCION DE DECANATO', 'COPIA SIMPLE DE RESOLUCION DE DECANATO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 15, 'CONSTANCIA FEDATEADA DE IDIOMA EXTRANJERO O NATIVO', 'CONSTANCIA FEDATEADA DE IDIOMA EXTRANJERO O NATIVO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'FOTO PASAPORTE', 'FOTO ACTUAL TAMAÑO PASAPORTE FONDO BLANCO, A COLOR CON EL LOGO DE LA UNT', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'COPIA DE DNI', 'COPIA SIMPLE LEGIBLE DEL DNI', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'DIPLOMA DE BACHILLER AUTENTICADA', 'COPIA DE LA DIPLOMA DE BACHILLER AUTENTICADA', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'CONSTANCIA DE NO ADEUDO', 'CONSTANCIA DE NO ADEUDO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'CONSTANCIA FEDATEADA DE IDIOMA EXTRANJERO O NATIVO', 'CONSTANCIA FEDATEADA DE IDIOMA EXTRANJERO O NATIVO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'CERTIFICADO DE ESTUDIOS', 'CERTIFICADO DE ESTUDIOS', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'ACTA DE SUSTENTACION', 'ACTA DE SUSTENTACION', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'CONSTANCIA DE EXPEDITO', 'CONSTANCIA DE EXPEDITO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'RESOLUCION DE DECANATO', 'RESOLUCION DE DECANATO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 16, 'CONSTANCIA DE PRIMERA MATRICULA Y EGRESADO', 'CONSTANCIA DE PRIMERA MATRICULA Y EGRESADO', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 17, 'FOTO CARNET', 'UNA FOTO CUMPLIENDO LOS REQUISITOS POR SUNEDU, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 18, 'FOTO CARNET', 'UNA FOTO CUMPLIENDO LOS REQUISITOS POR SUNEDU, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 18, 'DENUNCIA POLICIAL', 'DENUNCIA POLICIAL', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 19, 'FOTO CARNET', 'UNA FOTO CUMPLIENDO LOS REQUISITOS POR SUNEDU, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 20, 'FOTO CARNET', 'UNA FOTO CUMPLIENDO LOS REQUISITOS POR SUNEDU, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 20, 'DENUNCIA POLICIAL', 'DENUNCIA POLICIAL', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 21, 'FOTO CARNET', 'UNA FOTO CUMPLIENDO LOS REQUISITOS POR SUNEDU, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 22, 'FOTO CARNET', 'UNA FOTO CUMPLIENDO LOS REQUISITOS POR SUNEDU, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 22, 'DENUNCIA POLICIAL', 'DENUNCIA POLICIAL', 'pdf', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 23, 'FOTO CARNET', 'UNA FOTO CUMPLIENDO LOS REQUISITOS POR SUNEDU, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 24, 'FOTO CARNET', 'UNA FOTO CUMPLIENDO LOS REQUISITOS POR SUNEDU, EN FORMATO JPG', 'jpg', 1, DEFAULT);
INSERT INTO `uraa_tramite`.`requisito` (`idRequisito`, `idTipo_tramite_unidad`, `nombre`, `descripcion`, `extension`, `responsable`, `estado`) VALUES (DEFAULT, 24, 'DENUNCIA POLICIAL', 'DENUNCIA POLICIAL', 'pdf', 1, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`escuela`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 4, 1, 50, 366, 'ADMINISTRACION', 'ESCUELA PROFESIONAL DE ADMINISTRACION', 'ESCUELA PROFESIONAL DE ADMINISTRACION', 'ESCUELA PROFESIONAL DE ADMINISTRACION', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 1, 1, 51, 233, 'AGRONOMIA', 'ESCUELA PROFESIONAL DE AGRONOMIA', 'ESCUELA PROFESIONAL DE AGRONOMIA', 'ESCUELA PROFESIONAL DE AGRONOMIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 7, 1, 52, 78, 'ANTROPOLOGIA', 'ESCUELA PROFESIONAL DE ANTROPOLOGIA', 'ESCUELA PROFESIONAL DE ANTROPOLOGIA', 'ESCUELA PROFESIONAL DE ANTROPOLOGIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 7, 1, 53, 18, 'ARQUEOLOGIA', 'ESCUELA PROFESIONAL DE ARQUEOLOGIA', 'ESCUELA PROFESIONAL DE ARQUEOLOGIA', 'ESCUELA PROFESIONAL DE ARQUEOLOGIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 13, 1, 306, 209, 'ARQUITECTURA Y URBANISMO', 'ESCUELA PROFESIONAL DE ARQUITECTURA Y URBANISMO', 'ESCUELA PROFESIONAL DE ARQUITECTURA Y URBANISMO', 'ESCUELA PROFESIONAL DE ARQUITECTURA Y URBANISMO', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 2, 1, 83, 203, 'BIOLOGIA PESQUERA', 'ESCUELA PROFESIONAL DE BIOLOGIA PESQUERA', 'ESCUELA PROFESIONAL DE BIOLOGIA PESQUERA', 'ESCUELA PROFESIONAL DE BIOLOGIA PESQUERA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 2, 1, 54, 387, 'CIENCIAS BIOLOGICAS', 'ESCUELA PROFESIONAL DE CIENCIAS BIOLOGICAS', 'ESCUELA PROFESIONAL DE CIENCIAS BIOLOGICAS', 'ESCUELA PROFESIONAL DE CIENCIAS BIOLOGICAS', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 10, 1, 55, 162, 'CIENCIAS DE LA COMUNICACION', 'ESCUELA PROFESIONAL DE CIENCIAS DE LA COMUNICACION', 'ESCUELA PROFESIONAL DE CIENCIAS DE LA COMUNICACION', 'ESCUELA PROFESIONAL DE CIENCIAS DE LA COMUNICACION', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 8, 1, 307, 92, 'CIENCIAS POLITICAS Y GOBERNABILIDAD', 'ESCUELA PROFESIONAL DE CIENCIAS POLITICAS Y GOBERNABILIDAD', 'ESCUELA PROFESIONAL DE CIENCIAS POLITICAS Y GOBERNABILIDAD', 'ESCUELA PROFESIONAL DE CIENCIAS POLITICAS Y GOBERNABILIDAD', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 4, 1, 56, 255, 'CONTABILIDAD Y FINANZAS', 'ESCUELA PROFESIONAL DE CONTABILIDAD Y FINANZAS', 'ESCUELA PROFESIONAL DE CONTABILIDAD Y FINANZAS', 'ESCUELA PROFESIONAL DE CONTABILIDAD Y FINANZAS', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 8, 1, 57, 297, 'DERECHO Y CIENCIAS POLITICAS', 'ESCUELA PROFESIONAL DE DERECHO Y CIENCIAS POLITICAS', 'ESCUELA PROFESIONAL DE DERECHO Y CIENCIAS POLITICAS', 'ESCUELA PROFESIONAL DE DERECHO Y CIENCIAS POLITICAS', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 4, 1, 58, 142, 'ECONOMIA', 'ESCUELA PROFESIONAL DE ECONOMIA', 'ESCUELA PROFESIONAL DE ECONOMIA', 'ESCUELA PROFESIONAL DE ECONOMIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 10, 1, 59, 328, 'EDUCACION INICIAL', 'ESCUELA PROFESIONAL DE EDUCACION INICIAL', 'ESCUELA PROFESIONAL DE EDUCACION INICIAL', 'ESCUELA PROFESIONAL DE EDUCACION INICIAL', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 10, 1, 60, 355, 'EDUCACION PRIMARIA', 'ESCUELA PROFESIONAL DE EDUCACION PRIMARIA', 'ESCUELA PROFESIONAL DE EDUCACION PRIMARIA', 'ESCUELA PROFESIONAL DE EDUCACION PRIMARIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 10, 1, 61, 94, 'EDUCACION SECUNDARIA', 'ESCUELA PROFESIONAL DE EDUCACION SECUNDARIA', 'ESCUELA PROFESIONAL DE EDUCACION SECUNDARIA', 'ESCUELA PROFESIONAL DE EDUCACION SECUNDARIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 11, 1, 63, 270, 'ENFERMERIA', 'ESCUELA PROFESIONAL DE ENFERMERIA', 'ESCUELA PROFESIONAL DE ENFERMERIA', 'ESCUELA PROFESIONAL DE ENFERMERIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 5, 1, 72, 128, 'ESTADISTICA', 'ESCUELA PROFESIONAL DE ESTADISTICA', 'ESCUELA PROFESIONAL DE ESTADISTICA', 'ESCUELA PROFESIONAL DE ESTADISTICA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 16, 1, 62, 303, 'ESTOMATOLOGIA', 'ESCUELA PROFESIONAL DE ESTOMATOLOGIA', 'ESCUELA PROFESIONAL DE ESTOMATOLOGIA', 'ESCUELA PROFESIONAL DE ESTOMATOLOGIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 12, 1, 64, 358, 'FARMACIA Y BIOQUIMICA', 'ESCUELA PROFESIONAL DE FARMACIA Y BIOQUIMICA', 'ESCUELA PROFESIONAL DE FARMACIA Y BIOQUIMICA', 'ESCUELA PROFESIONAL DE FARMACIA Y BIOQUIMICA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 5, 1, 65, 6, 'FISICA', 'ESCUELA PROFESIONAL DE FISICA', 'ESCUELA PROFESIONAL DE FISICA', 'ESCUELA PROFESIONAL DE FISICA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 7, 1, 66, 15, 'HISTORIA', 'ESCUELA PROFESIONAL DE HISTORIA', 'ESCUELA PROFESIONAL DE HISTORIA', 'ESCUELA PROFESIONAL DE HISTORIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 5, 1, 75, 146, 'INFORMATICA', 'ESCUELA PROFESIONAL DE INFORMATICA', 'ESCUELA PROFESIONAL DE INFORMATICA', 'ESCUELA PROFESIONAL DE INFORMATICA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 1, 1, 67, 260, 'INGENIERIA AGRICOLA', 'ESCUELA PROFESIONAL DE INGENIERIA AGRICOLA', 'ESCUELA PROFESIONAL DE INGENIERIA AGRICOLA', 'ESCUELA PROFESIONAL DE INGENIERIA AGRICOLA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 1, 1, 68, 60, 'INGENIERIA AGROINDUSTRIAL', 'ESCUELA PROFESIONAL DE INGENIERIA AGROINDUSTRIAL', 'ESCUELA PROFESIONAL DE INGENIERIA AGROINDUSTRIAL', 'ESCUELA PROFESIONAL DE INGENIERIA AGROINDUSTRIAL', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 14, 1, 69, 300, 'INGENIERIA AMBIENTAL', 'ESCUELA PROFESIONAL DE INGENIERIA AMBIENTAL', 'ESCUELA PROFESIONAL DE INGENIERIA AMBIENTAL', 'ESCUELA PROFESIONAL DE INGENIERIA AMBIENTAL', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 13, 1, 305, 172, 'INGENIERIA CIVIL', 'ESCUELA PROFESIONAL DE INGENIERIA CIVIL', 'ESCUELA PROFESIONAL DE INGENIERIA CIVIL', 'ESCUELA PROFESIONAL DE INGENIERIA CIVIL', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 13, 1, 70, 8, 'INGENIERIA DE MATERIALES', 'ESCUELA PROFESIONAL DE INGENIERIA DE MATERIALES', 'ESCUELA PROFESIONAL DE INGENIERIA DE MATERIALES', 'ESCUELA PROFESIONAL DE INGENIERIA DE MATERIALES', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 13, 1, 71, 400, 'INGENIERIA DE MINAS', 'ESCUELA PROFESIONAL DE INGENIERIA DE MINAS', 'ESCUELA PROFESIONAL DE INGENIERIA DE MINAS', 'ESCUELA PROFESIONAL DE INGENIERIA DE MINAS', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 13, 1, 73, 21, 'INGENIERIA DE SISTEMAS', 'ESCUELA PROFESIONAL DE INGENIERIA DE SISTEMAS', 'ESCUELA PROFESIONAL DE INGENIERIA DE SISTEMAS', 'ESCUELA PROFESIONAL DE INGENIERIA DE SISTEMAS', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 13, 1, 74, 61, 'INGENIERIA INDUSTRIAL', 'ESCUELA PROFESIONAL DE INGENIERIA INDUSTRIAL', 'ESCUELA PROFESIONAL DE INGENIERIA INDUSTRIAL', 'ESCUELA PROFESIONAL DE INGENIERIA INDUSTRIAL', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 13, 1, 76, 222, 'INGENIERIA MECANICA', 'ESCUELA PROFESIONAL DE INGENIERIA MECANICA', 'ESCUELA PROFESIONAL DE INGENIERIA MECANICA', 'ESCUELA PROFESIONAL DE INGENIERIA MECANICA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 13, 1, 77, 119, 'INGENIERIA MECATRONICA', 'ESCUELA PROFESIONAL DE INGENIERIA MECATRONICA', 'ESCUELA PROFESIONAL DE INGENIERIA MECATRONICA', 'ESCUELA PROFESIONAL DE INGENIERIA MECATRONICA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 13, 1, 78, 515, 'INGENIERIA METALURGICA', 'ESCUELA PROFESIONAL DE INGENIERIA METALURGICA', 'ESCUELA PROFESIONAL DE INGENIERIA METALURGICA', 'ESCUELA PROFESIONAL DE INGENIERIA METALURGICA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 14, 1, 79, 168, 'INGENIERIA QUIMICA', 'ESCUELA PROFESIONAL DE INGENIERIA QUIMICA', 'ESCUELA PROFESIONAL DE INGENIERIA QUIMICA', 'ESCUELA PROFESIONAL DE INGENIERIA QUIMICA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 5, 1, 80, 214, 'MATEMATICA', 'ESCUELA PROFESIONAL DE MATEMATICA', 'ESCUELA PROFESIONAL DE MATEMATICA', 'ESCUELA PROFESIONAL DE MATEMATICA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 15, 1, 81, 194, 'MEDICINA', 'ESCUELA PROFESIONAL DE MEDICINA', 'ESCUELA PROFESIONAL DE MEDICINA', 'ESCUELA PROFESIONAL DE MEDICINA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 2, 1, 82, 212, 'MICROBIOLOGIA Y PARASITOLOGIA', 'ESCUELA PROFESIONAL DE MICROBIOLOGIA Y PARASITOLOGIA', 'ESCUELA PROFESIONAL DE MICROBIOLOGIA Y PARASITOLOGIA', 'ESCUELA PROFESIONAL DE MICROBIOLOGIA Y PARASITOLOGIA', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 7, 1, 84, 152, 'TRABAJO SOCIAL', 'ESCUELA PROFESIONAL DE TRABAJO SOCIAL', 'ESCUELA PROFESIONAL DE TRABAJO SOCIAL', 'ESCUELA PROFESIONAL DE TRABAJO SOCIAL', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 7, 1, 85, 159, 'TURISMO', 'ESCUELA PROFESIONAL DE TURISMO', 'ESCUELA PROFESIONAL DE TURISMO', 'ESCUELA PROFESIONAL DE TURISMO', 1);
INSERT INTO `uraa_tramite`.`escuela` (`idEscuela`, `idDependencia`, `idUnidad`, `idSGA_PREG`, `idSUV_PREG`, `nombre`, `denominacion`, `descripcion_grado`, `descripcion_titulo`, `estado`) VALUES (DEFAULT, 1, 1, 86, 145, 'ZOOTECNIA', 'ESCUELA PROFESIONAL DE ZOOTECNIA', 'ESCUELA PROFESIONAL DE ZOOTECNIA', 'ESCUELA PROFESIONAL DE ZOOTECNIA', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uraa_tramite`.`mencion`
-- -----------------------------------------------------
START TRANSACTION;
USE `uraa_tramite`;
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 1, 'CENTRO QUIRÚRGICO', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN CENTRO QUIRÚRGICO', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 2, 'CUIDADOS INTENSIVOS - ADULTO', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN CUIDADOS INTENSIVOS - ADULTO', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 3, 'CUIDADOS INTENSIVOS - PEDIATRÍA', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN CUIDADOS INTENSIVOS - PEDIATRÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 4, 'CUIDADOS INTENSIVOS - NEONATOLOGÍA', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN CUIDADOS INTENSIVOS - NEONATOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 5, 'EMERGENCIAS Y DESASTRES', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN EMERGENCIAS Y DESASTRES', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 6, 'ONCOLOGÍA', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN ONCOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 7, 'NEFROLOGÍA', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN NEFROLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 8, 'SALUD FAMILIAR Y COMUNITARIA', 'SEGUNDA ESPECIALIDAD PROFESIONAL ESPECIALISTA EN SALUD FAMILIAR Y COMUNITARIA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 9, 'SALUD OCUPACIONAL', 'SEGUNDA ESPECIALIDAD PROFESIONAL ESPECIALISTA EN SALUD OCUPACIONAL', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 10, 'GERENCIA Y ADMINISTRACIÓN EN SALUD', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN GERENCIA Y ADMINISTRACIÓN EN SALUD', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 17, 4, 11, 'GERIATRÍA Y GERONTOLOGÍA', 'SEGUNDA ESPECIALIDAD PROFESIONAL ESPECIALISTA  EN GERIATRÍA Y GERONTOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 12, 'ENTOMOLOGÍA MÉDICA Y CONTROL DE VECTORES', 'SEGUNDA ESPECIALIDAD EN ENTOMOLOGÍA MÉDICA Y CONTROL DE VECTORES', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 13, 'GESTIÓN DE LA BIODIVERSIDAD', 'SEGUNDA ESPECIALIDAD EN GESTIÓN DE LA BIODIVERSIDAD', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 14, 'EPIDEMIOLOGÍA', 'SEGUNDA ESPECIALIDAD EN EPIDEMIOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 15, 'LABORATORIO DE ANÁLISIS CLÍNICO Y BIOLÓGICOS', 'SEGUNDA ESPECIALIDAD EN LABORATORIO DE ANÁLISIS CLÍNICO Y BIOLÓGICOS', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 16, 'BIOLOGÍA MOLECULAR Y GENÉTICA', 'SEGUNDA ESPECIALIDAD EN BIOLOGÍA MOLECULAR Y GENÉTICA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 17, 'GESTIÓN AMBIENTAL', 'SEGUNDA ESPECIALIDAD EN GESTIÓN AMBIENTAL', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 18, 'BIOLOGÍA FORENSE', 'SEGUNDA ESPECIALIDAD EN BIOLOGÍA FORENSE', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 19, 'HEMOTERAPIA Y BANCO DE SANGRE', 'SEGUNDA ESPECIALIDAD EN HEMOTERAPIA Y BANCO DE SANGRE', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 20, 'GESTIÓN DE LA CALIDAD E INOCUIDAD ALIMENTARIA', 'SEGUNDA ESPECIALIDAD EN GESTIÓN DE LA CALIDAD E INOCUIDAD ALIMENTARIA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 19, 4, 21, 'ESTIMULACIÓN TEMPRANA', 'SEGUNDA ESPECIALIDAD EN ESTIMULACIÓN TEMPRANA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 20, 4, 22, 'CURRÍCULO Y ENSEÑANZA APRENDIZAJE', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN TECNOLOGÍA EDUCATIVA MENCIÓN CURRÍCULO Y ENSEÑANZA APRENDIZAJE', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 20, 4, 23, 'ADMINISTRACIÓN Y GERENCIA EDUCATIVA', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN TECNOLOGÍA EDUCATIVA MENCIÓN ADMINISTRACIÓN Y GERENCIA EDUCATIVA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 20, 4, 24, 'INFORMÁTICA EDUCATIVA', 'SEGUNDA ESPECIALIDAD PROFESIONAL EN TECNOLOGÍA EDUCATIVA MENCIÓN INFORMÁTICA EDUCATIVA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 25, 'EDUCACIÓN AMBIENTAL', 'SEGUNDA ESPECIALIDAD EN EDUCACIÓN AMBIENTAL', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 26, 'EVALUACIÓN DE IMPACTO AMBIENTAL', 'SEGUNDA ESPECIALIDAD: EVALUACIÓN DE IMPACTO AMBIENTAL', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 18, 4, 27, 'SANIDAD VEGETAL', 'SEGUNDA ESPECIALIDAD EN SANIDAD VEGETAL', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 21, 4, 28, 'TOXICOLOGÍA Y QUÍMICA FORENSE', 'SEGUNDA ESPECIALIDAD EN TOXICOLOGÍA Y QUÍMICA FORENSE', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 21, 4, 29, 'FARMACIA CLÍNICA', 'SEGUNDA ESPECIALIDAD EN FARMACIA CLÍNICA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 21, 4, 30, 'FARMACIA HOSPITALARIA Y COMUNITARIA', 'SEGUNDA ESPECIALIDAD EN FARMACIA HOSPITALARIA Y COMUNITARIA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 31, 'ANESTESIOLOGÍA', 'ANESTESIOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 32, 'CIRUGÍA GENERAL', 'CIRUGÍA GENERAL', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 33, 'DERMATOLOGÍA', 'DERMATOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 34, 'GASTROENTEROLOGÍA', 'GASTROENTEROLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 35, 'GINECOLOGÍA Y OBSTETRICIA', 'GINECOLOGÍA Y OBSTETRICIA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 36, 'MEDICINA DE EMERGENCIAS Y DESASTRES', 'MEDICINA DE EMERGENCIAS Y DESASTRES', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 37, 'MEDICINA DE ENFERMEDADES INFECCIOSAS Y TROPICALES', 'MEDICINA DE ENFERMEDADES INFECCIOSAS Y TROPICALES', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 38, 'MEDICINA FAMILIAR Y COMUNITARIA', 'MEDICINA FAMILIAR Y COMUNITARIA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 39, 'MEDICINA INTERNA', 'MEDICINA INTERNA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 40, 'NEUMOLOGÍA', 'NEUMOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 41, 'NEUROLOGÍA', 'NEUROLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 42, 'OFTALMOLOGÍA', 'OFTALMOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 43, 'ORTOPEDIA Y TRAUMATOLOGÍA', 'ORTOPEDIA Y TRAUMATOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 44, 'OTORRINOLARINGOLOGÍA', 'OTORRINOLARINGOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 45, 'PEDIATRÍA', 'PEDIATRÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 46, 'PSIQUIATRÍA', 'PSIQUIATRÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 47, 'RADIOLOGÍA', 'RADIOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 48, 'REUMATOLOGÍA', 'REUMATOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 49, 'NEONATOLOGÍA', 'SUB ESPECIALIDAD: NEONATOLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 50, 'UROLOGÍA', 'UROLOGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 51, 'MEDICINA INTENSIVA', 'MEDICINA INTENSIVA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 52, 'NEUROCIRUGÍA', 'NEUROCIRUGÍA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 53, 'PATOLOGIA', 'PATOLOGIA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 54, 'MEDICINA FISICA Y DE REHABILITACION', 'MEDICINA FISICA Y REHABILITACION (ACTUAL)', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 55, 'CIRUGÍA ONCOLÓGICA', 'CIRUGÍA ONCOLÓGICA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 56, 'MEDICINA ONCOLOGICA', 'MEDICINA ONCOLOGICA', 1);
INSERT INTO `uraa_tramite`.`mencion` (`idMencion`, `idDependencia`, `idUnidad`, `idSGA_SE`, `nombre`, `denominacion`, `estado`) VALUES (DEFAULT, 22, 4, 57, 'MEDICINA FISICA Y REHABILITACION', 'MEDICINA FISICA Y DE REHABILITACION', 1);

COMMIT;

